# Generated by Django 4.2 on 2024-08-10 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_dish_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailymenu',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='dish',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
